port: 8000

weaviate:
  host: "nysvnu.natappfree.cc"
  port: "80"

llm:
#  device: "cuda:0"
  device: "cpu"
  embedding_path: "D:/LLM/BAAI/bge-large-zh-v1.5"
#  embedding_path: "/root/autodl-tmp/llm/BAAI/bge-large-zh-v1.5"

vllm:
  model: "/root/autodl-tmp/llm/Qwen2-72B-Instruct-GPTQ-Int4"
  tensor_parallel_size: 4
  quantization: "gptq"
  seed: 42

mysql:
  host: "192.168.0.137"
  port: 3306
  user: "root"
  password: "mirandA123!@#"
  database: "test_xxlxdb"

redis:
  # 连接到Redis服务器的配置
  host: "192.168.0.188"
  port: 6379
  db: 12
  password: "aoji123!@#"
  # 最大重试次数和重试间隔（秒）
  max_retries: 5
  retry_delay: 3


